// proto/jira.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: jira.proto

package jira

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectKey    string                 `protobuf:"bytes,1,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_jira_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jira_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_jira_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_jira_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jira_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_jira_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_jira_proto protoreflect.FileDescriptor

const file_jira_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"jira.proto\x12\x04jira\".\n" +
	"\vSyncRequest\x12\x1f\n" +
	"\vproject_key\x18\x01 \x01(\tR\n" +
	"projectKey\"&\n" +
	"\fSyncResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2B\n" +
	"\vJiraService\x123\n" +
	"\n" +
	"SyncIssues\x12\x11.jira.SyncRequest\x1a\x12.jira.SyncResponseB\x0eZ\f./proto;jirab\x06proto3"

var (
	file_jira_proto_rawDescOnce sync.Once
	file_jira_proto_rawDescData []byte
)

func file_jira_proto_rawDescGZIP() []byte {
	file_jira_proto_rawDescOnce.Do(func() {
		file_jira_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jira_proto_rawDesc), len(file_jira_proto_rawDesc)))
	})
	return file_jira_proto_rawDescData
}

var file_jira_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jira_proto_goTypes = []any{
	(*SyncRequest)(nil),  // 0: jira.SyncRequest
	(*SyncResponse)(nil), // 1: jira.SyncResponse
}
var file_jira_proto_depIdxs = []int32{
	0, // 0: jira.JiraService.SyncIssues:input_type -> jira.SyncRequest
	1, // 1: jira.JiraService.SyncIssues:output_type -> jira.SyncResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jira_proto_init() }
func file_jira_proto_init() {
	if File_jira_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jira_proto_rawDesc), len(file_jira_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jira_proto_goTypes,
		DependencyIndexes: file_jira_proto_depIdxs,
		MessageInfos:      file_jira_proto_msgTypes,
	}.Build()
	File_jira_proto = out.File
	file_jira_proto_goTypes = nil
	file_jira_proto_depIdxs = nil
}
