// proto/jira.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: jira.proto

package jira

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JiraService_SyncIssues_FullMethodName = "/jira.JiraService/SyncIssues"
)

// JiraServiceClient is the client API for JiraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JiraServiceClient interface {
	SyncIssues(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type jiraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJiraServiceClient(cc grpc.ClientConnInterface) JiraServiceClient {
	return &jiraServiceClient{cc}
}

func (c *jiraServiceClient) SyncIssues(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, JiraService_SyncIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JiraServiceServer is the server API for JiraService service.
// All implementations must embed UnimplementedJiraServiceServer
// for forward compatibility.
type JiraServiceServer interface {
	SyncIssues(context.Context, *SyncRequest) (*SyncResponse, error)
	mustEmbedUnimplementedJiraServiceServer()
}

// UnimplementedJiraServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJiraServiceServer struct{}

func (UnimplementedJiraServiceServer) SyncIssues(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncIssues not implemented")
}
func (UnimplementedJiraServiceServer) mustEmbedUnimplementedJiraServiceServer() {}
func (UnimplementedJiraServiceServer) testEmbeddedByValue()                     {}

// UnsafeJiraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JiraServiceServer will
// result in compilation errors.
type UnsafeJiraServiceServer interface {
	mustEmbedUnimplementedJiraServiceServer()
}

func RegisterJiraServiceServer(s grpc.ServiceRegistrar, srv JiraServiceServer) {
	// If the following call pancis, it indicates UnimplementedJiraServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JiraService_ServiceDesc, srv)
}

func _JiraService_SyncIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiraServiceServer).SyncIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiraService_SyncIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiraServiceServer).SyncIssues(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JiraService_ServiceDesc is the grpc.ServiceDesc for JiraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JiraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jira.JiraService",
	HandlerType: (*JiraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncIssues",
			Handler:    _JiraService_SyncIssues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jira.proto",
}
