package internal

import "fmt"

type IssueIdea struct {
	Title       string
	Description string
}

func GenerateIssueIdea(prompt string) (*IssueIdea, error) {
	return &IssueIdea{
		Title:       fmt.Sprintf("Issue generated for prompt: %s", prompt),
		Description: "This is a detailed description generated by LLM.",
	}, nil
}
